language: cpp
dist: xenial
sudo: true
compiler: gcc

# Boost
addons:
  apt:
    packages: libboost-all-dev

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - wget https://github.com/eosio/eosio.cdt/releases/download/v1.7.0-rc1/eosio.cdt_1.7.0-rc1-ubuntu-18.04_amd64.deb
  - sudo apt install ./eosio.cdt_1.7.0-rc1-ubuntu-18.04_amd64.deb

script:
  - bash build.sh
